# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b3ac36412cddcfd4e14d8b5203e15c3aa4dcd2311e5882a4bede7b1752689b40e1e476d8b3161a25cf738dc68a616060b19118647161f6d559f57745881821b

test:
  secret_key_base: 5ab0361cd686f54b5a6daf444958b574f2fe5d1e1cdc22e805abac492174e601c24ab2237cdaea8d1f32c1f604de6fb108d56dd83677a9a177fae3d3b7e47f5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
